export const SCORING_CONFIG = {
  advertiserSafety: {
    baselineScore: 98,
    restrictedScore: 30,
    cautionScore: 70,
    restrictedRatioThreshold: 0.15,
    cautionRatioThreshold: 0.2,
  },
  automation: {
    baselineScore: 60,
    highScore: 90,
    lowScore: 30,
    mediumScore: 65,
    stockRatioThreshold: 0.15,
    presentationRatioThreshold: 0.25,
    personalityRatioThreshold: 0.15,
    bonusScore: 15,
    penaltyScore: 20,
    highPotentialThreshold: 75,
    lowPotentialThreshold: 45,
  },
  barrierEntry: {
    baselineScore: 55,
    highScore: 88,
    lowScore: 25,
    gearRatioThreshold: 0.25,
    basicRatioThreshold: 0.3,
    gearBonus: 20,
    basicReduction: 15,
    highBarrierThreshold: 75,
    lowBarrierThreshold: 45,
  },
  copyrightRisk: {
    baselineScore: 98,
    highRiskScore: 25,
    cautionScore: 70,
    mediaRatioThreshold: 0.2,
    gamingRatioThreshold: 0.2,
    fairUseRatioThreshold: 0.1,
    gamingCautionScore: 65,
    fairUseCautionScore: 75,
  },
  engagement: {
    baselineScore: 68,
    highScore: 90,
    lowScore: 35,
    highEngagementRatioThreshold: 20,
    lowEngagementRatioThreshold: 6,
    bonusScore: 15,
    penaltyScore: 20,
    highTierThreshold: 75,
    lowTierThreshold: 45,
  },
  revenueDiversity: {
    defaultDigital: 40,
    defaultPhysical: 50,
    defaultSponsor: 50,
    highDigital: 90,
    highPhysical: 90,
    highSponsor: 85,
    lowSponsor: 20,
    highTierThreshold: 75,
    lowTierThreshold: 45,
  },
  freshness: {
    fallbackEvergreenDays: 500,
    fallbackBalancedDays: 250,
    evergreenThreshold: 450,
    velocityThreshold: 120,
  }
};
